services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Http\:
        resource: '../src/Http/'
        tags: [ 'controller.service_arguments' ]

    App\Handler\:
        resource: '../src/Handler/'
        tags: [ messenger.message_handler ]
