services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Http\:
        resource: '../src/Http/'
        tags: [ 'controller.service_arguments' ]

    App\Handler\:
        resource: '../src/Handler/'
        tags: [ messenger.message_handler ]

    adapter.mailer.amazon_ses:
        class: App\Service\NotificationSenderAdapter\Email\SymfonyMailerBridge
        arguments:
            $transport: 'amazon_ses'
            $sender: '%env(EMAIL_SENDER)%'

    adapter.notifier.twilio:
        class: App\Service\NotificationSenderAdapter\SMS\SymfonyNotifierBridge
        arguments:
            $transport: 'twilio'

    App\Service\NotificationSenderAdapter\Push\HttpClient\SymfonyHttpClient:
        arguments:
            $token: '%env(PUSHY_API_TOKEN)%'

    App\Service\NotificationSender:
        calls:
            - ['addAdapter', ['@adapter.mailer.amazon_ses']]
            - ['addAdapter', ['@adapter.notifier.twilio']]
            - ['addAdapter', ['@App\Service\NotificationSenderAdapter\Push\PushyAdapter']]
